---
title: "Regulatory_pSer"
author: "Juan Carlos Aledo"
date: "5/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls())
library(ptm)
load("/Users/juancarlosaledo/ptm_outdropbox/ptm/htdocs/Rmd/vignettes/pprot.Rda")
```

```{r}
# list.reg <- function(id){
#   t <- reg.scan(id)
#   if (grepl("Sorry", t[1])){ # when there are no regulatory site in this protein
#     output <- -999 # an arbitrary label to indicate there is not reg sites
#   } else {
#     reg_sites <- c()
#     for (i in 1:nrow(t)){ # for each regulatory site
#       tt <- strsplit(t$modification[i], split = '-')[[1]]
#       if (tt[2] == 'p'){ # check that the regulatory site is a phosphosite
#         if (substring(tt[1], 1, 1) == 'S'){ # Make sure that the phosphosite is Ser
#           ttt <- substring(tt[1], 2, nchar(tt[1]))
#           reg_sites <- c(reg_sites, as.numeric(ttt))
#         }
#       } 
#     }
#     if (is.null(reg_sites)){
#       output <- -999 # an arbitrary label to indicate there is not reg phosphosites
#     } else {
#       output <- list(reg_sites) # from array to list
#     }
#   }
#   closeAllConnections()
#   return (output)
# }
```


```{r}
# pprot$reg <- NA
# # 1094, 5741, 15942
# for (i in 15942:nrow(pprot)){
#   print(i)
#   pprot$reg[i] <- list.reg(pprot$id[i])
# }
# 
# save(pprot, file = "/Users/juancarlosaledo/ptm_outdropbox/ptm/htdocs/Rmd/vignettes/pprot.Rda")
```

Filter the dataframe to build a new one containing only regularoty phosphoproteins:

```{r}
# pprot$particular <- FALSE # proteins with less number of non-reg pSer than reg pSer
# set.seed(123) # to make repetitive the pseudo-random manipulations
# regpprot <- pprot[1, 1:3] # as a primer to be extended
# regpprot$ctr[1] <- 212 # non-regulatory position to be used as control
# regpprot$target[1] <- regpprot$reg[1]
# counter <- 2
# for (i in 2:nrow(pprot)){
#   print(i)
#   t <- unlist(pprot$reg[i])
#   if (t[1] != -999){
# 
#     nr <- length(t) # number of regulatory sites
#     all <- pprot$pos[[i]] # all the positions (regulatory + non-regulatory)
#     re <- pprot$reg[[i]] # only regulatory positions
#     non <- setdiff(all, re) # only non-regulatory
#     if (length(non) < length(re)){
#       # particular <- c(particular, pprot$id[i])
#       pprot$particular[i] <- TRUE
#       next # jump to the next iteration (i + 1)
#     }
#     control <- sample(non, nr, replace = FALSE) # list with nr control positions
# 
#     for (j in 1:length(t)){
#       regpprot[counter, ] <- NA
#       regpprot$id[counter] <- pprot$id[i]
#       regpprot$pos[counter] <- pprot$pos[i]
#       regpprot$reg[counter] <- pprot$reg[i]
#       regpprot$target[counter] <- t[j]
#       regpprot$ctr[counter] <- control[j]
#       counter <- counter + 1
#     }
#   }
# }
# save(regpprot, file = "/Users/juancarlosaledo/ptm_outdropbox/ptm/htdocs/Rmd/vignettes/regpprot.Rda" )
# load("/Users/juancarlosaledo/ptm_outdropbox/ptm/htdocs/Rmd/vignettes/regpprot.Rda")
```

código alternativo más eficiente:

```{r}
# library(tidyr)
# df <- pprot[, 1:3]
# ## ------- Filtramos las filas que contienen -999 
# df$target <- df$reg
# df <- tidyr::unnest(df, target)
# ## ------- Filtramos las filas que contienen -999 
# df <- dplyr::filter(df, target != -999)
# ## ------- Filtramos las lineas en que 
# df$check <- TRUE
# for (i in 1:nrow(df)){
#   d <- setdiff(df$pos[[i]], df$reg[[i]])
#   if (length(df$reg[[i]]) > length(d)){
#     df$check[i] <- FALSE
#   }
# }
# df <- df[which(df$check == TRUE), -ncol(df)]
# 
# ## --- Randomly choosing a control serine position
# set.seed(123)
# df$ctr <- NA
# 
# list_of_protein <- as.character(df$id)
# 
# for (protein in list_of_protein){
#   lines <- which(df$id == protein)
#   first_line <- lines[1]
#   print(first_line)
#   set_to_be_sampled <- setdiff(df$pos[[first_line]], df$reg[[first_line]])
#   sample_size <- length(df$reg[[first_line]])
#   if (length(set_to_be_sampled) == 1){
#     df$ctr[first_line] <- set_to_be_sampled
#   } else {
#     my_sample <- sample(set_to_be_sampled, sample_size, replace=FALSE)
#     for (i in 1:length(lines)){
#       df$ctr[lines[i]] <- my_sample[i]
#     }
#   }
#   
# }
```

## Quality tests

```{r}
# df$quality <- NA
# 
# for (i in 1:nrow(df)){
#   print(i)
#   credit <- 5
#   # ctr and target must be different
#   if (df$target[i] == df$ctr[i]){
#     credit <- credit - 1
#   }
#   # ctr must belong to pos
#   if (! df$ctr[i] %in% df$pos[[i]]){
#     credit <- credit - 1
#   }
#   # target must belong to reg
#   if (! df$target[i] %in% df$reg[[i]]){
#     credit <- credit - 1
#   }
#   # residues at ctr and target positions should be Ser
#   seq <- ptm::get.seq(df$id[i])
#   if (! is.at(at = df$ctr[i], target = seq, aa = "S", uniprot = FALSE)){
#     credit <- credit - 1
#   }
#   if (! is.at(at = df$target[i], target = seq, aa = "S", uniprot = FALSE)){
#     credit <- credit - 1
#   }
#   
#   df$quality[i] <- credit
# }
# 
# # Remove rows that don't pass all the quality tests:
# to_be_removed <- which(df$quality != 5)
# regpprot <- df[- to_be_removed, ]
# save(regpprot, file = "./regpprot.Rda")
```



## Extracting the environments

```{r}
# library(ptm)
# regpprot$ctr_seq <- regpprot$pos_seq <- NA
# regpprot$check <- NA
# for (i in 1:nrow(regpprot)){
#   print(i)
#   seq <- ptm::get.seq(regpprot$id[i])
#   regpprot$check[i] <- is.at(regpprot$target[[i]], seq, "S", uniprot = FALSE)
#   regpprot$pos_seq[i] <- env.extract(seq, c = regpprot$target[[i]], r = 10)$Positive
#   regpprot$ctr_seq[i] <- env.extract(seq, c = regpprot$ctr[[i]], r = 10)$Positive
# }

# save(regpprot, file = "/Users/juancarlosaledo/ptm_outdropbox/ptm/htdocs/Rmd/vignettes/regpprot.Rda" )
```


## Results

```{r}
load("./regpprot.Rda")
positive <- env.matrices(regpprot$pos_seq)[[2]]
control <- env.matrices(regpprot$ctr_seq)[[2]]

positive <- positive[,-11]
control <- control[,-11]

Z <- env.Ztest(pos = positive, ctr = control, alpha = 0.0001)

Z1 <- Z[[1]]
Z2 <- Z[[2]]
Z3 <- Z[[3]]
```



```{r}
# pValue <- 0.0001
# cv <- stats::qnorm(1 - pValue) # critical value
# 
# # png(filename = "/Users/juancarlosaledo/Dropbox/Investigacion/Unpublished/Regulatory_pSer/Figures_pSer/R.png", width = 8, height = 5, units = "cm", res = 300)
# R <- c(Z1[15, 1:10], 0, Z1[11:20])
# pos <- -10:10
# plot(pos, R, ylim = c(-10, 17), ty = 'b', xlab = NA, ylab = NA)
# abline(-cv, 0, lty=2)
# abline(cv, 0, lty=2)
# points(x=c(-5, -3, -2), y = c(R[6], R[8], R[9]), col = "red", pch = 19) 
# # dev.off()
```

## Machine Learning

Local Features
```{r}
pser_reg <- regpprot[, c(1,4,7)]
names(pser_reg) <- c("id", "at", "env")
pser_reg$class <- "reg"

pser_ctr <- regpprot[, c(1,5,8)]
names(pser_ctr) <- c("id", "at", "env")
pser_ctr$class <- "ctr"

pser <- rbind(pser_reg, pser_ctr)
rm(pser_reg, pser_ctr)

pser$N_5A <- pser$N_5R <- pser$N_5N <- pser$N_5D <- pser$N_5C <- pser$N_5Q <- pser$N_5E <- pser$N_5G <- pser$N_5H <- pser$N_5I <- pser$N_5L <- pser$N_5K <- pser$N_5M <- pser$N_5F <- pser$N_5P <- pser$N_5S <- pser$N_5T <- pser$N_5W <- pser$N_5Y <- pser$N_5V <- pser$N_5X <- 0

pser$N_4A <- pser$N_4R <- pser$N_4N <- pser$N_4D <- pser$N_4C <- pser$N_4Q <- pser$N_4E <- pser$N_4G <- pser$N_4H <- pser$N_4I <- pser$N_4L <- pser$N_4K <- pser$N_4M <- pser$N_4F <- pser$N_4P <- pser$N_4S <- pser$N_4T <- pser$N_4W <- pser$N_4Y <- pser$N_4V <- pser$N_4X <- 0

pser$N_3A <- pser$N_3R <- pser$N_3N <- pser$N_3D <- pser$N_3C <- pser$N_3Q <- pser$N_3E <- pser$N_3G <- pser$N_3H <- pser$N_3I <- pser$N_3L <- pser$N_3K <- pser$N_3M <- pser$N_3F <- pser$N_3P <- pser$N_3S <- pser$N_3T <- pser$N_3W <- pser$N_3Y <- pser$N_3V <- pser$N_3X <- 0

pser$N_2A <- pser$N_2R <- pser$N_2N <- pser$N_2D <- pser$N_2C <- pser$N_2Q <- pser$N_2E <- pser$N_2G <- pser$N_2H <- pser$N_2I <- pser$N_2L <- pser$N_2K <- pser$N_2M <- pser$N_2F <- pser$N_2P <- pser$N_2S <- pser$N_2T <- pser$N_2W <- pser$N_2Y <- pser$N_2V <- pser$N_2X <- 0

pser$N_1A <- pser$N_1R <- pser$N_1N <- pser$N_1D <- pser$N_1C <- pser$N_1Q <- pser$N_1E <- pser$N_1G <- pser$N_1H <- pser$N_1I <- pser$N_1L <- pser$N_1K <- pser$N_1M <- pser$N_1F <- pser$N_1P <- pser$N_1S <- pser$N_1T <- pser$N_1W <- pser$N_1Y <- pser$N_1V <- pser$N_1X <- 0


pser$C_1A <- pser$C_1R <- pser$C_1N <- pser$C_1D <- pser$C_1C <- pser$C_1Q <- pser$C_1E <- pser$C_1G <- pser$C_1H <- pser$C_1I <- pser$C_1L <- pser$C_1K <- pser$C_1M <- pser$C_1F <- pser$C_1P <- pser$C_1S <- pser$C_1T <- pser$C_1W <- pser$C_1Y <- pser$C_1V <- pser$C_1X <- 0

pser$C_2A <- pser$C_2R <- pser$C_2N <- pser$C_2D <- pser$C_2C <- pser$C_2Q <- pser$C_2E <- pser$C_2G <- pser$C_2H <- pser$C_2I <- pser$C_2L <- pser$C_2K <- pser$C_2M <- pser$C_2F <- pser$C_2P <- pser$C_2S <- pser$C_2T <- pser$C_2W <- pser$C_2Y <- pser$C_2V <- pser$C_2X <- 0

pser$C_3A <- pser$C_3R <- pser$C_3N <- pser$C_3D <- pser$C_3C <- pser$C_3Q <- pser$C_3E <- pser$C_3G <- pser$C_3H <- pser$C_3I <- pser$C_3L <- pser$C_3K <- pser$C_3M <- pser$C_3F <- pser$C_3P <- pser$C_3S <- pser$C_3T <- pser$C_3W <- pser$C_3Y <- pser$C_3V <- pser$C_3X <- 0

pser$C_4A <- pser$C_4R <- pser$C_4N <- pser$C_4D <- pser$C_4C <- pser$C_4Q <- pser$C_4E <- pser$C_4G <- pser$C_4H <- pser$C_4I <- pser$C_4L <- pser$C_4K <- pser$C_4M <- pser$C_4F <- pser$C_4P <- pser$C_4S <- pser$C_4T <- pser$C_4W <- pser$C_4Y <- pser$C_4V <- pser$C_4X <-0

pser$C_5A <- pser$C_5R <- pser$C_5N <- pser$C_5D <- pser$C_5C <- pser$C_5Q <- pser$C_5E <- pser$C_5G <- pser$C_5H <- pser$C_5I <- pser$C_5L <- pser$C_5K <- pser$C_5M <- pser$C_5F <- pser$C_5P <- pser$C_5S <- pser$C_5T <- pser$C_5W <- pser$C_5Y <- pser$C_5V <- pser$C_5X <- 0

pser$C_6A <- pser$C_6R <- pser$C_6N <- pser$C_6D <- pser$C_6C <- pser$C_6Q <- pser$C_6E <- pser$C_6G <- pser$C_6H <- pser$C_6I <- pser$C_6L <- pser$C_6K <- pser$C_6M <- pser$C_6F <- pser$C_6P <- pser$C_6S <- pser$C_6T <- pser$C_6W <- pser$C_6Y <- pser$C_6V <- pser$C_6X <- 0

a <- as.character(ptm:::aai$aa)
a <- c(a, "X")

for (i in 1:nrow(pser)){
  
  print(i)
  env <- pser$env[i]
  
  n5 <- substr(env, 6, 6)
  v <- which(rev(a) == n5) # position within arrow of 20
  pser[i, 4 + v] <- 1
  
  n4 <- substr(env, 7, 7)
  v <- which(rev(a) == n4) # position within arrow of 20
  pser[i, 25 + v] <- 1
  
  n3 <- substr(env, 8, 8)
  v <- which(rev(a) == n3) # position within arrow of 20
  pser[i, 46 + v] <- 1
  
  n2 <- substr(env, 9, 9)
  v <- which(rev(a) == n2) # position within arrow of 20
  pser[i, 67 + v] <- 1
  
  n1 <- substr(env, 10, 10)
  v <- which(rev(a) == n1) # position within arrow of 20
  pser[i, 88 + v] <- 1
  
  c1 <- substr(env, 12, 12)
  v <- which(rev(a) == c1) # position within arrow of 20
  pser[i, 109 + v] <- 1
  
  c2 <- substr(env, 13, 13)
  v <- which(rev(a) == c2) # position within arrow of 20
  pser[i, 130 + v] <- 1
  
  c3 <- substr(env, 14, 14)
  v <- which(rev(a) == c3) # position within arrow of 20
  pser[i, 151 + v] <- 1
  
  c4 <- substr(env, 15, 15)
  v <- which(rev(a) == c4) # position within arrow of 20
  pser[i, 172 + v] <- 1
  
  c5 <- substr(env, 16, 16)
  v <- which(rev(a) == c5) # position within arrow of 20
  pser[i, 193 + v] <- 1
  
  c6 <- substr(env, 17, 17)
  v <- which(rev(a) == c6) # position within arrow of 20
  pser[i, 214 + v] <- 1
}

pser$check <- NA
for (i in 1:nrow(pser)){
  print(i)
  if (sum(pser[i, 5:235]) == 11){
    pser$check[i] <- TRUE
  } else {
    pser$check[i] <- FALSE
  }
}
table(pser$check)
```


