---
title: "Functional Categories"
author: "Juan Carlos Aledo"
date: "3/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Each MetO site can be assigned to one of three possible groups, depending on the answer to the following question:

Does the oxidation of this methionine has an effect on any biological property of the protein?

Group 1: The answer is "We do not know because it has not been addressed". This group is composed mainly for those MetO sites coming from high-througput studies and nothing is known about the effect of their sulfoxidation just because it has not been addressed.

Group 2: The answer is "No, we could not find any effect even though we searched for it". This group is formed for those methionines that are postulated to function as ROS sink (Proc. Natl. Acad. Sci. USA 93: 15036).

Group 3: The answer is "Yes, a change in some property has been described". This group is populated for those methionines that may fulfil a role in cellular signaling by affecting at least one of the following biological properties:

 - Gain of Activity
 - Loss of Activity
 - Gain of Protein-Protein Interaction
 - Loss of Protein-Protein Interaction
 - Effect on Protein Stability
 - Effect on Subcellular Location

On the other hand, each MetO site can be univocally assigned to one of 65 possible Funtional Categories (FC), according to the table shown below. It should be noted that in the following table a value of 1 for any of the six biological properties means that experimental evidence supporting such an effect has been published. On the contrary, a value of 0 only means that we have not found experimental evidence to support such an effect.


| FC | Group | Activity Gain | Activity Loss | PPI Gain | PPI Loss | Stability | Re-Localization |
| :--------:|:-----:| :--------:| :-------: | :------: | :------: | :-------: | :---: | 
| 1  | 1| 0|   0|   0|  0|  0|  0|
| 2  | 2| 0|   0|   0|  0|  0|  0|
| 3  | 3| 1|   0|   0|  0|  0|  0|
| 4  | 3| 0|   1|   0|  0|  0|  0|
| 5  | 3| 0|   0|   1|  0|  0|  0|
| 6  | 3| 0|   0|   0|  1|  0|  0| 
| 7  | 3| 0|   0|   0|  0|  1|  0| 
| 8  | 3| 0|   0|   0|  0|  0|  1| 
| 9  | 3| 0|   0|   0|  1|  0|  1|
| 10 | 3| 0|   0|   0|  1|  1|  0|
| 11 | 3| 0|   0|   1|  0|  0|  1|
| 12 | 3| 0|   0|   1|  0|  1|  0|
| 13 | 3| 0|   1|   0|  0|  0|  1|
| 14 | 3| 0|   1|   0|  0|  1|  0|
| 15 | 3| 1|   0|   0|  0|  0|  1|
| 16 | 3| 1|   0|   0|  0|  1|  0|
| 17 | 3| 0|   0|   1|  1|  0|  0|
| 18 | 3| 0|   1|   0|  1|  0|  0|
| 19 | 3| 0|   1|   1|  0|  0|  0|
| 20 | 3| 1|   0|   0|  1|  0|  0|
| 21 | 3| 1|   0|   1|  0|  0|  0|
| 22 | 3| 1|   1|   0|  0|  0|  0|
| 23 | 3| 0|   0|   0|  0|  1|  1|
| 24 | 3| 0|   0|   0|  1|  1|  1|
| 25 | 3| 0|   0|   1|  0|  1|  1|
| 26 | 3| 0|   1|   0|  0|  1|  1|
| 27 | 3| 1|   0|   0|  0|  1|  1|
| 28 | 3| 0|   0|   1|  1|  0|  1|
| 29 | 3| 0|   0|   1|  1|  1|  0|
| 30 | 3| 1|   1|   1|  0|  0|  0|
| 31 | 3| 0|   1|   0|  1|  0|  1|
| 32 | 3| 0|   1|   0|  1|  1|  0|
| 33 | 3| 0|   1|   1|  0|  0|  1|
| 34 | 3| 0|   1|   1|  0|  1|  0|
| 35 | 3| 1|   0|   0|  1|  0|  1|
| 36 | 3| 1|   0|   0|  1|  1|  0|
| 37 | 3| 1|   0|   1|  0|  0|  1|
| 38 | 3| 1|   0|   1|  0|  1|  0|
| 39 | 3| 1|   1|   0|  0|  0|  1|
| 40 | 3| 1|   1|   0|  0|  1|  0|
| 41 | 3| 0|   1|   1|  1|  0|  0|
| 42 | 3| 1|   0|   1|  1|  0|  0|
| 43 | 3| 1|   1|   0|  1|  0|  0|
| 44 | 3| 0|   0|   1|  1|  1|  1|
| 45 | 3| 0|   1|   0|  1|  1|  1|
| 46 | 3| 0|   1|   1|  0|  1|  1|
| 47 | 3| 1|   0|   0|  1|  1|  1|
| 48 | 3| 1|   0|   1|  0|  1|  1|
| 49 | 3| 1|   1|   0|  0|  1|  1|
| 50 | 3| 0|   1|   1|  1|  0|  1|
| 51 | 3| 0|   1|   1|  1|  1|  0|
| 52 | 3| 1|   0|   1|  1|  0|  1|
| 53 | 3| 1|   0|   1|  1|  1|  0|
| 54 | 3| 1|   1|   0|  1|  0|  1|
| 55 | 3| 1|   1|   0|  1|  1|  0|
| 56 | 3| 1|   1|   1|  1|  0|  0|
| 57 | 3| 1|   1|   1|  0|  0|  1|
| 58 | 3| 1|   1|   1|  0|  1|  0|
| 59 | 3| 0|   1|   1|  1|  1|  1|
| 60 | 3| 1|   0|   1|  1|  1|  1|
| 61 | 3| 1|   1|   0|  1|  1|  1|
| 62 | 3| 1|   1|   1|  0|  1|  1|
| 63 | 3| 1|   1|   1|  1|  0|  1|
| 64 | 3| 1|   1|   1|  1|  1|  0|
| 65 | 3| 1|   1|   1|  1|  1|  1|

